### ISSUE TITLE
Dart sdk version 

### ISSUE THREAD

**Issue by gunasekharravilla** [hoc081098/Movie-Ticket-Booking#46]
Running "flutter pub get" in datn...                            
The current Dart SDK version is 2.10.5.

Because stream_loader 1.1.0-nullsafety.1 requires SDK version >=2.12.0-0 <3.0.0 and no versions of stream_loader match >1.1.0-nullsafety.1 <2.0.0, stream_loader ^1.1.0-nullsafety.1 is forbidden.

So, because datn depends on stream_loader ^1.1.0-nullsafety.1, version solving failed.
pub get failed (1; So, because datn depends on stream_loader ^1.1.0-nullsafety.1, version solving failed.)
exit code 1

how change the sdk version

**Comment by hoc081098** [comment]
Dart >=2.12.0-0, you can use flutter channel dev

**Comment by gunasekharravilla** [comment]
Please provide clear wiki to run this project 

Include screenshots of movie admin app

**Comment by hoc081098** [comment]
Thanks @gunasekharravilla
