### ISSUE TITLE
flutter run 

### ISSUE THREAD

**Issue by gunasekharravilla** [hoc081098/Movie-Ticket-Booking#47]
flutter run
Multiple devices found:
Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.104
Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56
[1]: Chrome (chrome)
[2]: Edge (edge)
Please choose one (To quit, press "q/Q"): 1
Launching lib\main.dart on Chrome in debug mode...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_google_places-0.2.6/lib/src/flutter_google_places.dart:74:15: Error:
The method 'ancestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorStateOfType'.
      context.ancestorStateOfType(const TypeMatcher<PlacesAutocompleteState>());
              ^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Chrome...             34.4s
Failed to compile application.

**Comment by hoc081098** [comment]
Which version are you using?
The below is my flutter version
![image](https://user-images.githubusercontent.com/36917223/106540023-afabb200-6531-11eb-9a5f-e12ddaa00ee5.png)

**Comment by hoc081098** [comment]
Currently the app only supports for mobile platform

**Comment by gunasekharravilla** [comment]
C:\Users\Hp>flutter channel
Flutter channels:
  master
* dev
  beta
  stable

C:\Users\Hp>flutter --version
Flutter 1.26.0-17.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision c40e5294dd (4 days ago) • 2021-01-29 08:44:18 -0800
Engine • revision 5d3477eab4
Tools • Dart 2.12.0 (build 2.12.0-259.0.dev)


is that issue(The method 'ancestorStateOfType' isn't defined for the class 'BuildContext'.) because of version?

**Comment by hoc081098** [comment]
Seems `flutter_google_places` does not update to `dev` channel
