### ISSUE TITLE
User App notifications in notification bar  routing issue

### ISSUE THREAD

**Issue by gunasekharravilla** [hoc081098/Movie-Ticket-Booking#56]
When clicking ticket booking successful notification it's not routing to your reservations page simply opening the app from recent tabs

**Comment by gunasekharravilla** [comment]
Hey, nice buddy considering my issues to improve the quality of the product.

**Comment by gunasekharravilla** [comment]
Did you check Firebase Cloud Messaging is working fine? send the notifications to all users at a time

check in this link

https://console.firebase.google.com/u/0/project/<Project-Name>/notification

**Comment by gunasekharravilla** [comment]
firebase notification is working a fine great job

**Comment by hoc081098** [comment]
nice to hear that
